// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package logger

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func WireLogger() (*LoggerImpl, error) {
	loggerImpl, err := NewLogger()
	if err != nil {
		return nil, err
	}
	return loggerImpl, nil
}

// wire.go:

var WireSet = wire.NewSet(wire.Bind(new(Logger), new(*LoggerImpl)), WireLogger)
