// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package metrics

import (
	"github.com/google/wire"
	"github.com/wxing1292/wire/common/logger"
)

// Injectors from wire.go:

func WireMetrics(logger2 logger.Logger) (*MetricsImpl, error) {
	metricsImpl, err := NewMetrics(logger2)
	if err != nil {
		return nil, err
	}
	return metricsImpl, nil
}

// wire.go:

var WireSet = wire.NewSet(wire.Bind(new(Metrics), new(*MetricsImpl)), WireMetrics)
