// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/wxing1292/wire/common/cache"
	"github.com/wxing1292/wire/common/logger"
	"github.com/wxing1292/wire/common/metrics"
	"github.com/wxing1292/wire/common/service"
)

// Injectors from wire.go:

func WireService() (*service.ServiceImpl, error) {
	loggerImpl, err := logger.WireLogger()
	if err != nil {
		return nil, err
	}
	metricsImpl, err := metrics.WireMetrics(loggerImpl)
	if err != nil {
		return nil, err
	}
	cacheImpl, err := cache.StartCache(loggerImpl, metricsImpl)
	if err != nil {
		return nil, err
	}
	serviceImpl, err := service.StartService(cacheImpl, loggerImpl, metricsImpl)
	if err != nil {
		return nil, err
	}
	return serviceImpl, nil
}
