// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	"github.com/wxing1292/wire/common/logger"
	"github.com/wxing1292/wire/common/metrics"
)

// Injectors from wire.go:

func WireService(logger2 logger.Logger, metrics2 metrics.Metrics) (*ServiceImpl, error) {
	serviceImpl := NewService(metrics2, logger2)
	return serviceImpl, nil
}
